
export const SAVE_PROFILE_INVESTEE = 'SAVE_PROFILE_INVESTEE'
export const SAVE_PROFILE_EMPLOYER = 'SAVE_PROFILE_EMPLOYER'
export const SAVE_PROFILE_INFO = 'SAVE_PROFILE_INFO'
export const SAVE_INVESTOR = 'SAVE_INVESTOR'
export const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE'
