version: "2"
services:
  python:
    container_name: python
    image: python:2-slim
    environment:
      - CONFERENCE_DB_ENGINE=django.contrib.gis.db.backends.postgis
      - CONFERENCE_DB_NAME=conference
      - CONFERENCE_DB_USER=conference_admin
      - CONFERENCE_DB_PASSWORD=conference_password
      - CONFERENCE_DB_HOST=postgres
      - CONFERENCE_DB_PORT=5432
      - PYTHONUNBUFFERED=0
    ports:
      - 8001:8001
    volumes:
      - .:/conference
    command: sh /conference/run_python.sh
    links:
      - postgres
  postgres:
    image: mdillon/postgis:10-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=conference
      - POSTGRES_USER=conference_admin
      - POSTGRES_PASSWORD=conference_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./database/postgres:/var/lib/postgresql/data:z
