# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=3)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundingStage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TokenType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendees.Company')),
                ('max_ticket', models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=12, null=True)),
                ('min_ticket', models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=12, null=True)),
                ('funding_stages', models.ManyToManyField(to='attendees.FundingStage', blank=True)),
                ('giveaways', models.ManyToManyField(to='attendees.Giveaway', blank=True)),
                ('product_stages', models.ManyToManyField(to='attendees.ProductStage', blank=True)),
                ('token_types', models.ManyToManyField(to='attendees.TokenType', blank=True)),
            ],
            bases=('attendees.company',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendees.Company')),
                ('fundraising_amount', models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=12, null=True)),
                ('notable', models.TextField(blank=True, default='')),
                ('funding_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendees.FundingStage')),
                ('giveaway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendees.Giveaway')),
                ('product_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendees.ProductStage')),
                ('token_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendees.TokenType')),
            ],
            bases=('attendees.company',),
        ),
    ]
