# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 13:17
from __future__ import unicode_literals

from django.db import migrations


def create_funding_stages(apps, schema_editor):
    FundingStage = apps.get_model('attendees', 'FundingStage')
    FundingStage.objects.create(id=1, name='SEED')
    FundingStage.objects.create(id=2, name='PRE_ICO')
    FundingStage.objects.create(id=3, name='POST_ICO')


def create_giveaways(apps, schema_editor):
    Giveaway = apps.get_model('attendees', 'Giveaway')
    Giveaway.objects.create(id=1, name='TOKEN')
    Giveaway.objects.create(id=2, name='EQUITY')
    Giveaway.objects.create(id=3, name='BOTH')


def create_product_stages(apps, schema_editor):
    ProductStage = apps.get_model('attendees', 'ProductStage')
    ProductStage.objects.create(id=1, name='PRE_PRODUCT')
    ProductStage.objects.create(id=2, name='LIVE_PRODUCT')
    ProductStage.objects.create(id=3, name='LIVE_PRODUCT_WITH_REVENUE')


def create_token_types(apps, schema_editor):
    TokenType = apps.get_model('attendees', 'TokenType')
    TokenType.objects.create(id=1, name='PROTOCOL')
    TokenType.objects.create(id=2, name='UTILITY')
    TokenType.objects.create(id=3, name='SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_funding_stages),
        migrations.RunPython(create_giveaways),
        migrations.RunPython(create_product_stages),
        migrations.RunPython(create_token_types),
    ]
