# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 13:17
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import migrations
from rest_framework.authtoken.models import Token


def create_tokens(apps, schema_editor):
    for user in User.objects.all():
        Token.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_initial_data'),
    ]

    operations = [
        migrations.RunPython(create_tokens),
    ]
