# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


def create_skills(apps, schema_editor):
    Skill = apps.get_model('attendees', 'Skill')
    Skill.objects.create(id=1, name='.NET')
    Skill.objects.create(id=2, name='AI')
    Skill.objects.create(id=3, name='ASP.NET')
    Skill.objects.create(id=4, name='AWS')
    Skill.objects.create(id=5, name='Accounting Management')
    Skill.objects.create(id=6, name='Acquisition Valuation')
    Skill.objects.create(id=7, name='Advertising Management')
    Skill.objects.create(id=8, name='Advertising Strategy and Management')
    Skill.objects.create(id=9, name='Agile')
    Skill.objects.create(id=10, name='Algorithms')
    Skill.objects.create(id=11, name='Analytics')
    Skill.objects.create(id=12, name='Analyzing Business Requirements')
    Skill.objects.create(id=13, name='Android')
    Skill.objects.create(id=14, name='AngularJS')
    Skill.objects.create(id=15, name='App Design')
    Skill.objects.create(id=16, name='App Development')
    Skill.objects.create(id=17, name='Asset Management')
    Skill.objects.create(id=18, name='Audit Compliance')
    Skill.objects.create(id=19, name='Audit Regulation Awareness')
    Skill.objects.create(id=20, name='Azure')
    Skill.objects.create(id=21, name='B2B Marketing')
    Skill.objects.create(id=22, name='Backend Engineering')
    Skill.objects.create(id=23, name='Bash')
    Skill.objects.create(id=24, name='Behavioral Economics')
    Skill.objects.create(id=25, name='Benchmarking')
    Skill.objects.create(id=26, name='Bootstrap')
    Skill.objects.create(id=27, name='Brand Management')
    Skill.objects.create(id=28, name='Breakthrough Thinking')
    Skill.objects.create(id=29, name='Budget Control')
    Skill.objects.create(id=30, name='Business & Industry Knowledge')
    Skill.objects.create(id=31, name='Business Analysis')
    Skill.objects.create(id=32, name='Business Law')
    Skill.objects.create(id=33, name='Business Models')
    Skill.objects.create(id=34, name='Business Negotiations')
    Skill.objects.create(id=35, name='C')
    Skill.objects.create(id=36, name='C#')
    Skill.objects.create(id=37, name='C++')
    Skill.objects.create(id=38, name='CSS')
    Skill.objects.create(id=39, name='Change Impact Analysis')
    Skill.objects.create(id=40, name='Channels Management')
    Skill.objects.create(id=41, name='Charisma')
    Skill.objects.create(id=42, name='Chef')
    Skill.objects.create(id=43, name='Cloud')
    Skill.objects.create(id=44, name='Coaching')
    Skill.objects.create(id=45, name='Coding')
    Skill.objects.create(id=46, name='Command Line')
    Skill.objects.create(id=47, name='Communication')
    Skill.objects.create(id=48, name='Communications to Customers')
    Skill.objects.create(id=49, name='Communications to Investors')
    Skill.objects.create(id=50, name='Communications to Stakeholders')
    Skill.objects.create(id=51, name='Competitive Analysis')
    Skill.objects.create(id=52, name='Competitive Strategy')
    Skill.objects.create(id=53, name='Compliance')
    Skill.objects.create(id=54, name='Computer Science')
    Skill.objects.create(id=55, name='Continuous Improvement')
    Skill.objects.create(id=56, name='Continuous Integration')
    Skill.objects.create(id=57, name='Contract Law')
    Skill.objects.create(id=58, name='Contract Management')
    Skill.objects.create(id=59, name='Corporate Financial Management')
    Skill.objects.create(id=60, name='Corporate Governance')
    Skill.objects.create(id=61, name='Corporate Innovation')
    Skill.objects.create(id=62, name='Corporate Restructuring')
    Skill.objects.create(id=63, name='Corporate Social Responsibility')
    Skill.objects.create(id=64, name='Cost Management')
    Skill.objects.create(id=65, name='Cost/Benefit Analysis')
    Skill.objects.create(id=66, name='Counterparty Risk Management')
    Skill.objects.create(id=67, name='Creative Questioning')
    Skill.objects.create(id=68, name='Crisis Management')
    Skill.objects.create(id=69, name='Cross-Cultural Management')
    Skill.objects.create(id=70, name='Cryptography')
    Skill.objects.create(id=71, name='Data Analytics')
    Skill.objects.create(id=72, name='Data Science')
    Skill.objects.create(id=73, name='Data-driven decisions')
    Skill.objects.create(id=74, name='Database Design')
    Skill.objects.create(id=75, name='Dealing with Ambiguity')
    Skill.objects.create(id=76, name='Decisions Making')
    Skill.objects.create(id=77, name='Delegation')
    Skill.objects.create(id=78, name='Design')
    Skill.objects.create(id=79, name='Developing Business Plans')
    Skill.objects.create(id=80, name='Developing Requirements')
    Skill.objects.create(id=81, name='Development')
    Skill.objects.create(id=82, name='Diplomacy')
    Skill.objects.create(id=83, name='Dispute Resolution')
    Skill.objects.create(id=84, name='Dividend Policy')
    Skill.objects.create(id=85, name='Django')
    Skill.objects.create(id=86, name='Docker')
    Skill.objects.create(id=87, name='Economics')
    Skill.objects.create(id=88, name='Engineering')
    Skill.objects.create(id=89, name='Entrepreneurship')
    Skill.objects.create(id=90, name='Ethereum')
    Skill.objects.create(id=91, name='Expense Management')
    Skill.objects.create(id=92, name='Fair Competition')
    Skill.objects.create(id=93, name='Familiar with UI Toolkits and Frameworks')
    Skill.objects.create(id=94, name='Finance')
    Skill.objects.create(id=95, name='Financial Audit')
    Skill.objects.create(id=96, name='Financial Forecasting')
    Skill.objects.create(id=97, name='Financial Governance')
    Skill.objects.create(id=98, name='Financial Management')
    Skill.objects.create(id=99, name='Financial Management in a Dynamic Regulatory Environment')
    Skill.objects.create(id=100, name='Financial Modeling')
    Skill.objects.create(id=101, name='Financing')
    Skill.objects.create(id=102, name='Finding Order in Chaos')
    Skill.objects.create(id=103, name='Forecasting')
    Skill.objects.create(id=104, name='Frontend Engineering')
    Skill.objects.create(id=105, name='Full Stack Engineering')
    Skill.objects.create(id=106, name='Fundraising')
    Skill.objects.create(id=107, name='Game Theory')
    Skill.objects.create(id=108, name='Gap Analysis')
    Skill.objects.create(id=109, name='Gap Identification')
    Skill.objects.create(id=110, name='Git')
    Skill.objects.create(id=111, name='Go')
    Skill.objects.create(id=112, name='Graph Databases')
    Skill.objects.create(id=113, name='HR Management')
    Skill.objects.create(id=114, name='HTML')
    Skill.objects.create(id=115, name='Hadoop')
    Skill.objects.create(id=116, name='Hiring')
    Skill.objects.create(id=117, name='Human Resources')
    Skill.objects.create(id=118, name='ICO Marketing')
    Skill.objects.create(id=119, name='Influencing')
    Skill.objects.create(id=120, name='Influencing Skills')
    Skill.objects.create(id=121, name='Information Analysis')
    Skill.objects.create(id=122, name='Innovation')
    Skill.objects.create(id=123, name='Intellectual Property Law')
    Skill.objects.create(id=124, name='International Business')
    Skill.objects.create(id=125, name='International Marketing')
    Skill.objects.create(id=126, name='Interviewing')
    Skill.objects.create(id=127, name='Invision')
    Skill.objects.create(id=128, name='Java')
    Skill.objects.create(id=129, name='Javascript')
    Skill.objects.create(id=130, name='Kaizen')
    Skill.objects.create(id=131, name='Knowledge')
    Skill.objects.create(id=132, name='Knowledge Management')
    Skill.objects.create(id=133, name='Leadership')
    Skill.objects.create(id=134, name='Leading Change')
    Skill.objects.create(id=135, name='Liability Risks')
    Skill.objects.create(id=136, name='Liability Valuation')
    Skill.objects.create(id=137, name='Linux/Unix')
    Skill.objects.create(id=138, name='Logistics')
    Skill.objects.create(id=139, name='Long-Term Financial Management')
    Skill.objects.create(id=140, name='M&A Economics')
    Skill.objects.create(id=141, name='M&A Finance')
    Skill.objects.create(id=142, name='M&A Law')
    Skill.objects.create(id=143, name='ML')
    Skill.objects.create(id=144, name='Machine Learning')
    Skill.objects.create(id=145, name='Managing Budgets')
    Skill.objects.create(id=146, name='Managing Change')
    Skill.objects.create(id=147, name='Managing Difficult People')
    Skill.objects.create(id=148, name='Managing Incentives')
    Skill.objects.create(id=149, name='Managing Risk')
    Skill.objects.create(id=150, name='Managing Teams')
    Skill.objects.create(id=151, name='Managing Top Talent')
    Skill.objects.create(id=152, name='Managing Uncertainty & Ambiguity')
    Skill.objects.create(id=153, name='MapReduce')
    Skill.objects.create(id=154, name='Market Knowledge')
    Skill.objects.create(id=155, name='Market Research')
    Skill.objects.create(id=156, name='Marketing')
    Skill.objects.create(id=157, name='Mechanism Design')
    Skill.objects.create(id=158, name='Mentoring')
    Skill.objects.create(id=159, name='Mobile Development')
    Skill.objects.create(id=160, name='Multi-channel Communications')
    Skill.objects.create(id=161, name='Multinational Marketing Strategy')
    Skill.objects.create(id=162, name='NLP')
    Skill.objects.create(id=163, name='Natural Language Processing')
    Skill.objects.create(id=164, name='Negotiating')
    Skill.objects.create(id=165, name='NoSQL')
    Skill.objects.create(id=166, name='Node.js')
    Skill.objects.create(id=167, name='Node.js Experience')
    Skill.objects.create(id=168, name='NumPy')
    Skill.objects.create(id=169, name='Objective-C')
    Skill.objects.create(id=170, name='Operational Analysis')
    Skill.objects.create(id=171, name='Operations Management')
    Skill.objects.create(id=172, name='PHP')
    Skill.objects.create(id=173, name='PR')
    Skill.objects.create(id=174, name='Perl')
    Skill.objects.create(id=175, name='Photoshop')
    Skill.objects.create(id=176, name='Planning')
    Skill.objects.create(id=177, name='Political Savvy')
    Skill.objects.create(id=178, name='Politics')
    Skill.objects.create(id=179, name='Previous Experience Working Within an Agile Scrum Team')
    Skill.objects.create(id=180, name='Price Strategy')
    Skill.objects.create(id=181, name='Prioritization')
    Skill.objects.create(id=182, name='Problem Solving')
    Skill.objects.create(id=183, name='Product Development')
    Skill.objects.create(id=184, name='Program Management')
    Skill.objects.create(id=185, name='Project Management')
    Skill.objects.create(id=186, name='Prototyping')
    Skill.objects.create(id=187, name='Providing Feedback')
    Skill.objects.create(id=188, name='Public Relations')
    Skill.objects.create(id=189, name='Public Speaking')
    Skill.objects.create(id=190, name='Puppet')
    Skill.objects.create(id=191, name='QA')
    Skill.objects.create(id=192, name='Quality Assurance')
    Skill.objects.create(id=193, name='Raising Capital')
    Skill.objects.create(id=194, name='Rapid Prototyping')
    Skill.objects.create(id=195, name='ReactJS')
    Skill.objects.create(id=196, name='ReactNative')
    Skill.objects.create(id=197, name='Recruiting')
    Skill.objects.create(id=198, name='Redux')
    Skill.objects.create(id=199, name='Regulatory Compliance')
    Skill.objects.create(id=200, name='Reputation Management')
    Skill.objects.create(id=201, name='Resource Allocation')
    Skill.objects.create(id=202, name='Resource Management')
    Skill.objects.create(id=203, name='Resource Planning')
    Skill.objects.create(id=204, name='Responsive Design')
    Skill.objects.create(id=205, name='Revenue Management')
    Skill.objects.create(id=206, name='Risk Assessments')
    Skill.objects.create(id=207, name='Risk Management')
    Skill.objects.create(id=208, name='Ruby')
    Skill.objects.create(id=209, name='Ruby on Rails')
    Skill.objects.create(id=210, name='SQL')
    Skill.objects.create(id=211, name='Sales Force Management')
    Skill.objects.create(id=212, name='Sales Management')
    Skill.objects.create(id=213, name='Sales Strategy')
    Skill.objects.create(id=214, name='Sales Tactics')
    Skill.objects.create(id=215, name='Salesforce')
    Skill.objects.create(id=216, name='Sass')
    Skill.objects.create(id=217, name='Scala')
    Skill.objects.create(id=218, name='Scalability')
    Skill.objects.create(id=219, name='Scheduling')
    Skill.objects.create(id=220, name='Scrum')
    Skill.objects.create(id=221, name='Selenium')
    Skill.objects.create(id=222, name='Shell')
    Skill.objects.create(id=223, name='Sketch')
    Skill.objects.create(id=224, name='Smart Contract Development')
    Skill.objects.create(id=225, name='Software')
    Skill.objects.create(id=226, name='Software Architecture')
    Skill.objects.create(id=227, name='Solidity')
    Skill.objects.create(id=228, name='Statistics')
    Skill.objects.create(id=229, name='Strategic Analysis')
    Skill.objects.create(id=230, name='Supervision')
    Skill.objects.create(id=231, name='Supply Chain Management')
    Skill.objects.create(id=232, name='Sustainability')
    Skill.objects.create(id=233, name='Sustainability and Corporate Social Responsibility')
    Skill.objects.create(id=234, name='Swift')
    Skill.objects.create(id=235, name='Task Planning')
    Skill.objects.create(id=236, name='Tax Strategy')
    Skill.objects.create(id=237, name='Team Building')
    Skill.objects.create(id=238, name='TensorFlow')
    Skill.objects.create(id=239, name='Testing')
    Skill.objects.create(id=240, name='Theano')
    Skill.objects.create(id=241, name='Tokenomics')
    Skill.objects.create(id=242, name='Tools')
    Skill.objects.create(id=243, name='Training')
    Skill.objects.create(id=244, name='UI Design')
    Skill.objects.create(id=245, name='UX Design')
    Skill.objects.create(id=246, name='Unit Testing')
    Skill.objects.create(id=247, name='Vagrant')
    Skill.objects.create(id=248, name='Venture Capital')
    Skill.objects.create(id=249, name='Web')
    Skill.objects.create(id=250, name='Web Design')
    Skill.objects.create(id=251, name='Web Development')
    Skill.objects.create(id=252, name='WebHooks')
    Skill.objects.create(id=253, name='WebRTC')
    Skill.objects.create(id=254, name='Writing Whitepapers')
    Skill.objects.create(id=255, name='jQuery')


def create_traits(apps, schema_editor):
    Trait = apps.get_model('attendees', 'Trait')
    Trait.objects.create(id=1, name='Accomplished')
    Trait.objects.create(id=2, name='Accurate')
    Trait.objects.create(id=3, name='Action Focused')
    Trait.objects.create(id=4, name='Adaptable')
    Trait.objects.create(id=5, name='Administered')
    Trait.objects.create(id=6, name='Advanced')
    Trait.objects.create(id=7, name='Agile')
    Trait.objects.create(id=8, name='Ambitious')
    Trait.objects.create(id=9, name='Autonomous')
    Trait.objects.create(id=10, name='Balanced')
    Trait.objects.create(id=11, name='Calm')
    Trait.objects.create(id=12, name='Capable')
    Trait.objects.create(id=13, name='Charismatic')
    Trait.objects.create(id=14, name='Clear spoken')
    Trait.objects.create(id=15, name='Collaborative')
    Trait.objects.create(id=16, name='Collected')
    Trait.objects.create(id=17, name='Communicative')
    Trait.objects.create(id=18, name='Competitive')
    Trait.objects.create(id=19, name='Confident')
    Trait.objects.create(id=20, name='Consistent')
    Trait.objects.create(id=21, name='Cool under pressure')
    Trait.objects.create(id=22, name='Cooperative')
    Trait.objects.create(id=23, name='Creative')
    Trait.objects.create(id=24, name='Critical Thinker')
    Trait.objects.create(id=25, name='Culturally Conscious')
    Trait.objects.create(id=26, name='Inspiring')
    Trait.objects.create(id=27, name='Curious')
    Trait.objects.create(id=28, name='Detail Oriented')
    Trait.objects.create(id=29, name='Determined')
    Trait.objects.create(id=30, name='Diplomatic')
    Trait.objects.create(id=31, name='Directed')
    Trait.objects.create(id=32, name='Dynamic')
    Trait.objects.create(id=33, name='Effective')
    Trait.objects.create(id=34, name='Efficient')
    Trait.objects.create(id=35, name='Energized')
    Trait.objects.create(id=36, name='Enthusiastic')
    Trait.objects.create(id=37, name='Entrepreneurial Thinking')
    Trait.objects.create(id=38, name='Ethical')
    Trait.objects.create(id=39, name='Excellent Problem Solver')
    Trait.objects.create(id=40, name='Extroverted')
    Trait.objects.create(id=41, name='Fearless')
    Trait.objects.create(id=42, name='Flexible')
    Trait.objects.create(id=43, name='Fluent')
    Trait.objects.create(id=44, name='Focused')
    Trait.objects.create(id=45, name='Go Getter')
    Trait.objects.create(id=46, name='Goal Oriented')
    Trait.objects.create(id=47, name='Hardworking')
    Trait.objects.create(id=48, name='High Endurance')
    Trait.objects.create(id=49, name='Innovative')
    Trait.objects.create(id=50, name='Integral')
    Trait.objects.create(id=51, name='Integrity')
    Trait.objects.create(id=52, name='Intelligent')
    Trait.objects.create(id=53, name='Introverted')
    Trait.objects.create(id=54, name='Intuitive')
    Trait.objects.create(id=55, name='Investigative')
    Trait.objects.create(id=56, name='Judgmental')
    Trait.objects.create(id=57, name='Leadership')
    Trait.objects.create(id=58, name='Mindful')
    Trait.objects.create(id=59, name='Motivated')
    Trait.objects.create(id=60, name='Motivating')
    Trait.objects.create(id=61, name='Objective')
    Trait.objects.create(id=62, name='Optimized')
    Trait.objects.create(id=63, name='Ordered')
    Trait.objects.create(id=64, name='Organized')
    Trait.objects.create(id=65, name='Passionate')
    Trait.objects.create(id=66, name='Persuasive')
    Trait.objects.create(id=67, name='Proactive')
    Trait.objects.create(id=68, name='Problem solver')
    Trait.objects.create(id=69, name='Productive')
    Trait.objects.create(id=70, name='Professional')
    Trait.objects.create(id=71, name='Prompt')
    Trait.objects.create(id=72, name='Punctual')
    Trait.objects.create(id=73, name='Qualified')
    Trait.objects.create(id=74, name='Quantified')
    Trait.objects.create(id=75, name='Quick learner')
    Trait.objects.create(id=76, name='Reliable')
    Trait.objects.create(id=77, name='Resourceful')
    Trait.objects.create(id=78, name='Respectable')
    Trait.objects.create(id=79, name='Respectful')
    Trait.objects.create(id=80, name='Responsive')
    Trait.objects.create(id=81, name='Security Mindset')
    Trait.objects.create(id=82, name='Self-Aware')
    Trait.objects.create(id=83, name='Decisive')
    Trait.objects.create(id=84, name='Enthusiastic')
    Trait.objects.create(id=85, name='Fair')
    Trait.objects.create(id=86, name='Selfless')
    Trait.objects.create(id=87, name='Specialized')
    Trait.objects.create(id=88, name='Strategic')
    Trait.objects.create(id=89, name='Streamlined')
    Trait.objects.create(id=90, name='Tactical')
    Trait.objects.create(id=91, name='Task Oriented')
    Trait.objects.create(id=92, name='Team Player')
    Trait.objects.create(id=93, name='Transformative')
    Trait.objects.create(id=94, name='Troubleshooter')
    Trait.objects.create(id=95, name='Unifying')
    Trait.objects.create(id=96, name='Visionary')
    Trait.objects.create(id=97, name='Well Spoken')
    Trait.objects.create(id=98, name='Well-written')


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0009_jobrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.IntegerField(serialize=False, verbose_name='ID', primary_key=True)),
                ('name', models.CharField(max_length=56)),
            ],
        ),
        migrations.RunPython(create_skills),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.IntegerField(serialize=False, verbose_name='ID', primary_key=True)),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.RunPython(create_traits),
    ]
