# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-29 12:38
from __future__ import unicode_literals

from django.db import migrations


def migrate_countries(apps, schema_editor):
    Project = apps.get_model('attendees', 'Project')
    for project in Project.objects.all():
        if project.legal_country or project.main_country:
            if project.legal_country:
                project.legal_country = project.legal_country.upper()
            if project.main_country:
                project.main_country = project.main_country.upper()
            project.save()
    Investor = apps.get_model('attendees', 'Investor')
    for investor in Investor.objects.all():
        if investor.nationality:
            investor.nationality = investor.nationality.upper()
            investor.save()
    Professional = apps.get_model('attendees', 'Professional')
    for professional in Professional.objects.all():
        if professional.country:
            professional.country = professional.country.upper()
            professional.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0031_auto_20180827_0954'),
    ]

    operations = [
        migrations.RunPython(migrate_countries),
    ]
