export const SET_INVESTOR_FILTERS = 'SET_INVESTOR_FILTERS';
export const SET_PROJECT_FILTERS = 'SET_PROJECT_FILTERS';
export const SET_PROFESSIONAL_FILTERS = 'SET_PROFESSIONAL_FILTERS';
export const SET_JOB_FILTERS = 'SET_JOB_FILTERS';
export const LOAD_MATCH_FILTERS = 'LOAD_MATCH_FILTERS';
export const LOAD_MATCH_FILTERS_ERROR = 'LOAD_MATCH_FILTERS_ERROR';
export const LOAD_MATCH_FILTERS_SUCCESS = 'LOAD_MATCH_FILTERS_SUCCESS';
export const CLEAR = 'FILTER_CLEAR';
