export const SET_INVESTOR_FILTERS = 'SET_INVESTOR_FILTERS';
export const SET_PROJECT_FILTERS = 'SET_PROJECT_FILTERS';
export const SET_JOB_FILTERS = 'SET_JOB_FILTERS'
export const CLEAR = 'FILTER_CLEAR'
